language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

env:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1

# Clones WordPress and configures our testing environment.
before_script:
  # Setup Coveralls
  - phpenv local 5.5
  - composer install --no-interaction
  - phpenv local --unset

  - npm install

  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml antivirus.php
  - phpunit --coverage-clover clover.xml
  - npx eslint js/script.js

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
