language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
    allow_failures:
      - php: nightly

env:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1

before_install:
  - nvm install 12

# Clones WordPress and configures our testing environment.
before_script:
  # Setup Coveralls
  - phpenv local 5.5
  - composer install --no-interaction
  - phpenv local --unset

  - npm install

  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - composer build
  - composer lint-all
  - phpunit --coverage-clover clover.xml

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
